image:
  repository: ghcr.io/kuan-platform-lab/order-service
  tag: sha-f8aaa1f
env:
  PAYMENT_URL: http://payment-service-dev:8082
externalSecret:
  enabled: true
  key: platform-dev/rds/orders
  template:
    DB_URL: "jdbc:postgresql://{{ .host }}:{{ .port }}/{{ .dbname }}"
    DB_USER: "{{ .username }}"
    DB_PASSWORD: "{{ .password }}"
ingress:
  enabled: true
  host: order.dev.lab.local     # qua Cloudflare Tunnel thì đổi thành hostname thật
