{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "bs.name" . }}
  labels: {{- include "bs.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecret.store }}
  target:
    name: {{ include "bs.name" . }}-secrets
    template:
      engineVersion: v2
      data:
        {{- range $k, $v := .Values.externalSecret.template }}
        {{ $k }}: {{ $v | quote }}
        {{- end }}
  dataFrom:
    - extract:
        key: {{ required "externalSecret.key is required" .Values.externalSecret.key }}
{{- end }}
